trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 0: Checkout your repo (must-have!)
- checkout: self

# Step 1: Set up Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Step 2: Install dependencies
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install unittest-xml-reporting
  displayName: 'Install dependencies'

# Step 3: Run tests and generate JUnit XML report
- script: 
    source venv/bin/activate
    mkdir -p test-results
    python -m xmlrunner discover -s pipline.tests -o test-results
  displayName: 'Run Unit Tests and Output JUnit XML'
# Step 4: Publish test results to Azure DevOps
- script: |
    source venv/bin/activate
    mkdir -p test-results
    python -m xmlrunner discover -s pipline.tests -o test-results
    echo "Directory structure after test run:"
    ls -R test-results
  displayName: 'Run Unit Tests and Output JUnit XML'
# Step 5: Deploy to Azure Web App
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'RupeshAzureConnection'
    appName: 'samplepythonapprupesh'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'runFromPackage'